<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ben">
  <xacro:arg name="namespace" default="ben"/>
  <xacro:property name="namespace" value="$(arg namespace)" scope="global" />

  <xacro:property name="mass" value="950" />
  
  <xacro:property name="cg_x" value="-0.911" />
  <xacro:property name="cg_y" value="-0.018" />
  <xacro:property name="cg_z" value="-0.182" />
  
  <xacro:property name="ixx" value="280.97548467" />
  <xacro:property name="ixy" value="-9.237803" />
  <xacro:property name="ixz" value="-2.02566202" />
  <xacro:property name="iyy" value="866.01489076" />
  <xacro:property name="iyz" value="-0.43969229" />
  <xacro:property name="izz" value="793.7913527" />
  
  <xacro:property name="buoyancy_offset" value=".35" />
  
  <link name="${namespace}/base_link">
  </link>
  
  <joint name="${namespace}_base_to_motion_sensor_joint" type="fixed">
      <parent link="${namespace}/base_link"/>
      <child link="${namespace}/motion_sensor"/>
      <origin xyz="${- cg_x} ${- cg_y} ${buoyancy_offset - cg_z}" rpy="0 0 0"/>
  </joint>
  
  <link name="${namespace}/motion_sensor">
    <visual>
        <geometry>
            <mesh filename="package://ben_description/models/meshes/BEN_shell.dae"/>
        </geometry>
    </visual>
    
    <!-- footprint: 2.65, 0
                    2.6,  0.1
                    2.4,  0.4
                    1.9,  0.6
                    1.0,  0.85
                    -1.3, 0.85
                    -1.35, 0.4
                    -1.6, 0.35
                    (repeat symetrically for other side)
                    (Meters relative to base frame)

                     -->
    <collision>
        <geometry>
            <mesh filename="package://ben_description/models/meshes/BEN_convex_hull.dae"/>
        </geometry>
    </collision>
    
    <inertial>
        <!--Values obtained from OnShape-->
        <origin xyz="${cg_x} ${cg_y} ${cg_z}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
            ixx="${ixx}" ixy="${ixy}" ixz="${ixz}"
            iyy="${iyy}" iyz="${iyz}"
            izz="${izz}"/>
    </inertial>
    
  </link>

  <xacro:include filename="$(find ben_description)/urdf/sensors/lidar.xacro" />
  <xacro:ben_lidar name="lidar" x="-1.98" y="0.0" z="1.403"/>

  <xacro:include filename="$(find ben_description)/urdf/sensors/radar.xacro" />
  <xacro:ben_radar name="radar" x="-1.8" y="0.0" z="1.3"/>

  <xacro:include filename="$(find ben_description)/urdf/sensors/pano_array.xacro" />
  <xacro:pano_array name="pano" x="-1.98" z="1.266"/>

  <xacro:include filename="$(find ben_description)/urdf/sensors/oem_gps.xacro" />
  <xacro:oem_gps name="gps" x="-0.953" y="0.103" z="0.628"/>

  <xacro:include filename="$(find ben_description)/urdf/sensors/oem_heading_sensor.xacro" />
  <xacro:oem_heading_sensor name="heading"/>
  
  <xacro:include filename="$(find ben_description)/urdf/sensors/forward_camera.xacro" />
  <xacro:forward_camera name="forward_camera" y="0.1" x="-1.307" z="0.742" P="${radians(0)}" />

  
</robot>
